#CodeAssist project settings
#Mon Sep 28 02:51:11 GMT+08:00 2026
tree.expanded.Project=root\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/nimbus-weather/app/src/main/res\nmodule\:app\nworkspace\nroot\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/nimbus-weather/app/src/main/kotlin
